//  Sánchez Plazola José Abraham
//  30/06/2021
//  Ventana para el registro de las ventas realizadas con conexión a base de datos

package Vistas;

import Modelos.Conexion;
import static Modelos.Modelo_Ventas.cantidad;
import static Modelos.Modelo_Ventas.precio;
import static Modelos.Modelo_Ventas.total;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Personal
 */
public class Registro_Ventas extends javax.swing.JFrame {
    /**
     * Creates new form Registro_Ventas
*/
  // Modelo_Ventas modelo = new Modelo_Ventas();
    
    public Registro_Ventas() {
        initComponents();
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    DefaultTableModel dtm;
    Object[] o = new Object[5];
    private Conexion conexion = new Conexion();
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCodigo = new javax.swing.JTextField();
        lblCodigo = new javax.swing.JLabel();
        btnBuscarProducto = new javax.swing.JButton();
        lblProducto = new javax.swing.JLabel();
        lblExistenca = new javax.swing.JLabel();
        lblNombreVariable = new javax.swing.JLabel();
        lblExistenciaVariable = new javax.swing.JLabel();
        btnAdd = new javax.swing.JButton();
        lblCantidad = new javax.swing.JLabel();
        txtCantidad = new javax.swing.JTextField();
        lblTelefono = new javax.swing.JLabel();
        TxtTelefono = new javax.swing.JTextField();
        btnBuscarCliente = new javax.swing.JButton();
        lblNombreCliente = new javax.swing.JLabel();
        lblNombreClienteVariable = new javax.swing.JLabel();
        btnConfirmar = new javax.swing.JButton();
        separador = new javax.swing.JSeparator();
        lblConfirmacion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        lblFinal = new javax.swing.JLabel();
        lblFinalVariable = new javax.swing.JLabel();
        btnFinalizar = new javax.swing.JButton();
        lblFolio = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar ventas");

        txtCodigo.setEditable(false);
        txtCodigo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        lblCodigo.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblCodigo.setText("Código del producto:");

        btnBuscarProducto.setText("Buscar");
        btnBuscarProducto.setEnabled(false);
        btnBuscarProducto.setPreferredSize(new java.awt.Dimension(69, 23));
        btnBuscarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarProductoActionPerformed(evt);
            }
        });

        lblProducto.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblProducto.setText("Nombre del producto:");

        lblExistenca.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblExistenca.setText("Existencia:");

        lblNombreVariable.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblNombreVariable.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        lblExistenciaVariable.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblExistenciaVariable.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnAdd.setText("Añadir");
        btnAdd.setEnabled(false);
        btnAdd.setPreferredSize(new java.awt.Dimension(69, 23));
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        lblCantidad.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblCantidad.setText("Cantidad:");

        txtCantidad.setEditable(false);
        txtCantidad.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        lblTelefono.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblTelefono.setText("Teléfono del cliente:");

        TxtTelefono.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        btnBuscarCliente.setText("Buscar");
        btnBuscarCliente.setPreferredSize(new java.awt.Dimension(69, 23));
        btnBuscarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarClienteActionPerformed(evt);
            }
        });

        lblNombreCliente.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblNombreCliente.setText("Nombre del cliente:");

        lblNombreClienteVariable.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblNombreClienteVariable.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnConfirmar.setText("Confirmar");
        btnConfirmar.setPreferredSize(new java.awt.Dimension(69, 23));
        btnConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConfirmarActionPerformed(evt);
            }
        });

        lblConfirmacion.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblConfirmacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Producto", "Precio Individual", "Cantidad", "Precio final"
            }
        ));
        tabla.setEnabled(false);
        jScrollPane1.setViewportView(tabla);

        lblFinal.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblFinal.setText("Precio final:");

        lblFinalVariable.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblFinalVariable.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        btnFinalizar.setText("Finalizar");
        btnFinalizar.setPreferredSize(new java.awt.Dimension(69, 23));
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });

        lblFolio.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblFolio.setText("IdFactura:");

        lblID.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblID.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnBack.setText("Regresar");
        btnBack.setPreferredSize(new java.awt.Dimension(69, 23));
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addComponent(lblConfirmacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblCodigo)
                                        .addComponent(lblExistenca)
                                        .addComponent(lblProducto)
                                        .addComponent(lblCantidad))
                                    .addComponent(lblNombreCliente, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTelefono, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblFolio, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(TxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblNombreVariable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(lblNombreClienteVariable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblExistenciaVariable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(166, 166, 166))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblID)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(12, 12, 12)
                                                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGap(0, 0, Short.MAX_VALUE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(lblFinal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblFinalVariable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefono)
                    .addComponent(TxtTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblNombreCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblNombreVariable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(separador, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCodigo)
                    .addComponent(txtCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProducto)
                    .addComponent(lblNombreClienteVariable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblExistenca)
                    .addComponent(lblExistenciaVariable))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblID)
                    .addComponent(lblFolio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCantidad))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFinal)
                    .addComponent(lblFinalVariable))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFinalizar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblConfirmacion))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void btnBuscarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarProductoActionPerformed
    
    }//GEN-LAST:event_btnBuscarProductoActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
    añadirTabla1();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnBuscarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarClienteActionPerformed
       //lblNombreVariable.setText(modelo.nombre);
    }//GEN-LAST:event_btnBuscarClienteActionPerformed

    private void btnConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConfirmarActionPerformed
      txtCodigo.setEditable(true);
      txtCantidad.setEditable(true);
      btnBuscarProducto.setEnabled(true);
      btnAdd.setEnabled(true);
      tabla.setEnabled(true);
    }//GEN-LAST:event_btnConfirmarActionPerformed

    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBackActionPerformed
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registro_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registro_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registro_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registro_Ventas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registro_Ventas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JTextField TxtTelefono;
    public javax.swing.JButton btnAdd;
    public javax.swing.JButton btnBack;
    public javax.swing.JButton btnBuscarCliente;
    public javax.swing.JButton btnBuscarProducto;
    public javax.swing.JButton btnConfirmar;
    public javax.swing.JButton btnFinalizar;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JLabel lblCantidad;
    public javax.swing.JLabel lblCodigo;
    private javax.swing.JLabel lblConfirmacion;
    public javax.swing.JLabel lblExistenca;
    public javax.swing.JLabel lblExistenciaVariable;
    public javax.swing.JLabel lblFinal;
    public javax.swing.JLabel lblFinalVariable;
    public javax.swing.JLabel lblFolio;
    public javax.swing.JLabel lblID;
    public javax.swing.JLabel lblNombreCliente;
    public javax.swing.JLabel lblNombreClienteVariable;
    public javax.swing.JLabel lblNombreVariable;
    public javax.swing.JLabel lblProducto;
    public javax.swing.JLabel lblTelefono;
    public javax.swing.JSeparator separador;
    public javax.swing.JTable tabla;
    public javax.swing.JTextField txtCantidad;
    public javax.swing.JTextField txtCodigo;
    // End of variables declaration//GEN-END:variables

    public boolean añadirTabla(int Cantidad) {
        dtm = (DefaultTableModel) tabla.getModel();
        try{
            Connection con = conexion.abrirConexion();
            Statement stmt = con.createStatement();
            ResultSet rs, id;
            String rs2;
            String IdCodigo =  txtCodigo.getText();

            id = stmt.executeQuery("SELECT Precio FROM albumes WHERE IdAlbumes = "+IdCodigo); //Devuelve el precio en base a su id
            while (id.next()){
              rs2 = id.getString("Precio");
             precio = Double.parseDouble(rs2);
             cantidad = Cantidad;
             total = precio * cantidad;
             o[0] = IdCodigo;
             o[1] = lblNombreClienteVariable.getText();
             o[2] = precio;
             o[3] = cantidad;
             o[4] = total;
        }dtm.addRow(o);
        double sumatoria1=0.0;
        int totalRow= tabla.getRowCount();
        totalRow-=1;
        for(int i=0;i<=(totalRow);i++)
        {
           double sumatoria= Double.parseDouble(String.valueOf(tabla.getValueAt(i,4)));
            //en la parte de arriba indica el primer parametro la fila y el segundo la columna la cual se esta manejando
          sumatoria1+=sumatoria;
          String s=String.valueOf(sumatoria1); 
          lblFinalVariable.setText(s);
       conexion.cerrarConexion(con);
            return true;
        }}catch(SQLException e){
            System.out.print("error" +e);
            return false;
        }
        return false;
    }

    private void añadirTabla1() {
        String cantidad = txtCantidad.getText();
        Integer i = Integer.parseInt(cantidad);
        añadirTabla(i);
    }
}
