//  Osuna Pimienta Melani
//  30/06/2021
//  Ventana para el registro de una nueva cuenta en el reproductor de música
package Vistas;

/**
 *
 * @author cowpr
 */
public class Reproductor_Registro extends javax.swing.JFrame {

    /**
     * Creates new form InterfazRegistro
     */
    public Reproductor_Registro() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TituloLabel = new javax.swing.JLabel();
        ContraText = new javax.swing.JPasswordField();
        RegButt = new javax.swing.JButton();
        UsuarioText = new javax.swing.JTextField();
        Telefono = new javax.swing.JTextField();
        ContraCText = new javax.swing.JPasswordField();
        CorreoLabel = new javax.swing.JLabel();
        ContraLabel = new javax.swing.JLabel();
        ConfContraLabel = new javax.swing.JLabel();
        UsuarioLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registro");

        TituloLabel.setFont(new java.awt.Font("Gadugi", 0, 18)); // NOI18N
        TituloLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TituloLabel.setText("Registrar Usuario");
        TituloLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        ContraText.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        ContraText.setToolTipText("Contraseña");

        RegButt.setText("Registrarse");
        RegButt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegButtActionPerformed(evt);
            }
        });

        UsuarioText.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        UsuarioText.setToolTipText("Nombre de Usuario");
        UsuarioText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        Telefono.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        Telefono.setToolTipText("Correo Electrónico");
        Telefono.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        ContraCText.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        ContraCText.setToolTipText("Confirme Su Contraseña");

        CorreoLabel.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        CorreoLabel.setText("Teléfono");

        ContraLabel.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        ContraLabel.setText("Contraseña");

        ConfContraLabel.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        ConfContraLabel.setText("Confirmar Contraseña");

        UsuarioLabel.setFont(new java.awt.Font("Gadugi", 0, 12)); // NOI18N
        UsuarioLabel.setText("Nombre De Usuario");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TituloLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CorreoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(ContraLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(ConfContraLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(UsuarioLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(UsuarioText)
                    .addComponent(Telefono)
                    .addComponent(ContraText)
                    .addComponent(ContraCText, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(RegButt, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(253, 253, 253))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TituloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(UsuarioText, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(UsuarioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CorreoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContraText, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ContraLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ContraCText, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ConfContraLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(RegButt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(95, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegButtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegButtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RegButtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reproductor_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reproductor_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reproductor_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reproductor_Registro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reproductor_Registro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel ConfContraLabel;
    public javax.swing.JPasswordField ContraCText;
    public javax.swing.JLabel ContraLabel;
    public javax.swing.JPasswordField ContraText;
    public javax.swing.JLabel CorreoLabel;
    public javax.swing.JButton RegButt;
    public javax.swing.JTextField Telefono;
    public javax.swing.JLabel TituloLabel;
    public javax.swing.JLabel UsuarioLabel;
    public javax.swing.JTextField UsuarioText;
    // End of variables declaration//GEN-END:variables
}
